name: Build Lazarus Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install FreePascal and Lazarus
        run: |
          choco install fpc
          choco install lazarus

      - name: Compile Lazarus Project
        run: fpc project1.lpr  # Zastąp 'project1.lpr' nazwą swojego pliku głównego w projekcie Lazarus

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-program
          path: project1.exe  # Zastąp nazwą swojego pliku wynikowego
