name: Build Lazarus Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Lazarus & FPC
      run: |
        choco install lazarus --version=2.2.4 --yes
        echo "C:\\lazarus" >> $env:GITHUB_PATH

    - name: Build Project
      run: |
        lazbuild project1.lpi

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: TimerApp.exe
        path: project1.exe
