name: Build Lazarus Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Lazarus
      run: choco install lazarus --yes

    - name: Build project
      run: |
        fpc project1.lpr

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: TimerApp
        path: project1.exe
