name: Build Lazarus Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Free Pascal and Lazarus
      run: |
        sudo apt update
        sudo apt install -y fpc fpc-source lazarus lcl

    - name: Compile project
      run: fpc -Fu/usr/lib/lazarus/2.2.0/lcl/units/x86_64-linux project1.lpr

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: TimerApp
        path: project1
